### ISSUE TITLE
syncstore test still failing with couchbase

### ISSUE THREAD

**Issue by zaach** [mozilla/picl-server#49]
This test fails when running the full test suite using couchbase, but curiously succeeds when running only the `test/syncstore.js` tests:

```
  1) syncstore will reject writes if conditional on an old version:

  AssertionError: {"code":24} == null
      at items.two.deleted (/Users/zcarter/moz/picl-server/test/syncstore.js:116:20)
      at module.exports.connect.syncstore.setItems (/Users/zcarter/moz/picl-server/lib/syncstore.js:235:23)
      at module.exports.connect.couchbase.connect.bucket.set.cas (/Users/zcarter/moz/picl-server/lib/kvstore/couchbase.js:33:20)
      at Array.handleValue [as 0] (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/bucket.js:66:17)
      at getParsedHandler (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/bucket.js:520:12)
      at Object._singleGet (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/bucket.js:73:20)
      at Object.get (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/bucket.js:82:24)
      at module.exports.connect.couchbase.connect.bucket.set.cas (/Users/zcarter/moz/picl-server/lib/kvstore/couchbase.js:28:16)
      at /Users/zcarter/moz/picl-server/node_modules/couchbase/lib/couchbase.js:9:18
      at exports.connect.connection.on.errObj.code (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/couchbase.js:121:13)
      at exports.create (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/bucket.js:397:9)
      at Request.exports.create.fields [as _callback] (/Users/zcarter/moz/picl-server/node_modules/couchbase/lib/bucket.js:324:21)
      at Request.init.self.callback (/Users/zcarter/moz/picl-server/node_modules/couchbase/node_modules/request/main.js:122:22)
      at Request.EventEmitter.emit (events.js:99:17)
      at Request.<anonymous> (/Users/zcarter/moz/picl-server/node_modules/couchbase/node_modules/request/main.js:655:16)
      at Request.EventEmitter.emit (events.js:126:20)
      at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/Users/zcarter/moz/picl-server/node_modules/couchbase/node_modules/request/main.js:617:14)
      at IncomingMessage.EventEmitter.emit (events.js:126:20)
      at IncomingMessage._emitEnd (http.js:366:10)
      at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
      at Socket.socketOnData [as ondata] (http.js:1472:20)
      at TCP.onread (net.js:404:27)
```

**Comment by zaach** [comment]
Not sure what happened, but I can't reproduce now.
